import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function header() {
  return (<div className='flex m-2 justify-between items-center'>
    <Link href="/">
      Home
    </Link>
    <Link href="/blocks/new" className="border p-2 border rounded">
      New
    </Link>
  </div>);
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='container mx-auto px-12'>
          {header()}
          {children}
        </div>
      </body>
    </html>
  )
}
